### ISSUE TITLE
create sim from existing Treant

### ISSUE THREAD

**Issue by kain88-de** [datreant/MDSynthesis#60]
Can I convert a treant into a sim to keep all his tags and categories?

**Comment by dotsdl** [comment]
This can be done by changing the name of the state file from `Treant.<uuid>.json` to `Sim.<uuid>.json`. There isn't a built-in programmatic way to do this since at the moment it would confuse different instances of the same `Treant` if one such instance made this change. I'm definitely interested in elegant ways of making this work.

**Comment by kain88-de** [comment]
Really? Then what distinguishes a Sim from a Treant?

**Comment by orbeckst** [comment]
Additional methods/attributes related to MDAnalysis.Universe handling (and, at the moment, deprecated stuff to handle resnums).

**Comment by dotsdl** [comment]
This is being addressed by #70, which fixes number #65. Closing.
