### ISSUE TITLE
Move to MDAnalysis org

### ISSUE THREAD

**Issue by kain88-de** [datreant/MDSynthesis#67]
Should we move this to the MDAnlaysis organization? @orbeckst @jbarnoud @richardjgowers

**Comment by jbarnoud** [comment]
What would be the gain compared to have it in the datreant one? From what I see, it is much more sensitive to changes in datreant than to changes in MDAnalysis. Also, it is a good demo to show that datreant can be extended with field-specific logic.

**Comment by richardjgowers** [comment]
It might be a better fit than here, people are more likely to use MDA then migrate to also use MDS, rather than datreant->MDS.  But it'd be a shame for datreant to lose the flagship example of how to make dtr domain specific.

**Comment by jbarnoud** [comment]
It is @dotsdl baby. What does he think about the question?

**Comment by dotsdl** [comment]
Hey all, good discussion so far. Here are my thoughts.

I intend to continue maintaining `datreant.core` for the foreseeable future, since I think it occupies a pretty unique space and is also general-purpose as a filesystem interface. That said, speaking for myself I'm moving out of the biophysics sphere and into a different domain entirely, so I don't see myself having the time or the motivation to work as much on MD-specific things.

Given that, and given that MDS is more of an appealing tool for the MD community than someone that might like to use `datreant` (@richardjgowers point), I think moving it under the MDAnalysis umbrella is appropriate. This could lower the barrier to further developing it to suit the needs of the MDAnalysis community, in particular things like automatic persistence of topology information and the like. Of course this move only makes sense if there's interest among the MDAnalysis devs to maintain this (yet another) package.

**Comment by dotsdl** [comment]
Also, to be clear, we want to get MDS into a 1.0-ready shape pretty soon, probably close to MDA 1.0. There are some changes that need to happen in `datreant.core` first to make all this work, so unfortunately there are a lot of linked pieces here.

**Comment by orbeckst** [comment]
@dotsdl can you ~~open an issue~~ add to #64  outlining these "moving pieces", specifically, what needs to happen for MDS 1.0? 

I would really like to see MDS in a state where it can be used and does not require constant attention.

**Comment by orbeckst** [comment]
Just wanted to add that I like MDSynthesis to live in a stable 1.0 state because it fills a small but important niche (and we use it in the lab...). I would also see some appeal in moving it to MDAnalysis to increase the potential audience, to encourage tools such as @fiona-naughton 's  proposed wham tools MDAnalysis/mdanalysis#923 which would use bundles MDAnalysis/mdanalysis#900, and it also fits into the MD* "brand" ;-) – but as said before, that's very much @dotsdl 's choice if he wants to move it (and then the MDAnalysis devs if they want to take it).

**Comment by orbeckst** [comment]
We could fork the MDS repo to the MDAnalysis org. Someone would need to occasionally pull changes so that they are in sync but the development volume on MDS isn't huge so that's probably not a major issue. It would expose MDS to both communities.

**Comment by orbeckst** [comment]
Given that we are now discouraging new users from using MDS for new projects and instead recommend datreant (see conversation in #80), I think this issue is moot. 

(Please re-open if you have a different opinion or if I have overlooked something.)
